project:
  type: website
website:
  search: 
    location: navbar
    type: overlay
  margin-header: subscribe.html
  google-analytics: 
    tracking-id: "G-EGKBDV26WE"
    anonymize-ip: true
  cookie-consent: true
  title: "eLucidate science"
  navbar:
    background: "#111418"
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog
      - href: about.qmd
        text: CV
    right:
      - icon: github
        href: https://github.com/metahag
      - icon: instagram
        href: https://www.instagram.com/znanstvena_revolucija
format:
  html:
    theme: styles.scss
    page-layout: full
editor: source

