project:
  type: website
website:
  search: 
    location: navbar
    type: overlay
  margin-header: subscribe.html
  google-analytics: 
    tracking-id: "G-EGKBDV26WE"
    anonymize-ip: true
  cookie-consent: true
  title: "eLucidate science"
  navbar:
    background: "#111418"
    right:
      - about.qmd
      - icon: github
        href: https://github.com/metahag
      - icon: instagram
        href: https://www.instagram.com/znanstvena_revolucija
format:
  html:
    theme: styles.scss


editor: source

