---
title: "Reproducibility gatekeepers"
description: "Common reasons your code doesn't reproduce and how to fix it"
author: "Lucija Batinović"
date: "2024-xx-xx"
categories:
  - reproducibility
editor: source
execute: 
  eval: false
number-sections: true
draft: true
---

Working as a reproducibility coordinator at [*Meta-Psychology*](https://open.lnu.se/index.php/metapsychology) has given me invaluable experience and free insight coding conventions. It has also directly caused multiple migraines in the past 3 years (see DAG in Figure 1). Making your analysis code (easily) reproducible is hard, particularly when you're not a software engineer and the operating systems seem to be conspiring against you every step of the way. 

After reproducing dozens of papers, I have found some culprits more often than others, and this post is brought to you by the frustration caused by container-emulators and the urge to make code more easily reproducible.

## What prevents reproducing results in one click?

### Paths
To start off, I should say that defining what counts as reproduced is not really defined or agreed upon (to the best of my knowledge I claim, like a true academic), which makes this fairly arbitrary, but the idea of perfect reproduction should perhaps be: follow given instructions to run the code and run it without any tweaks, i.e., with one click.

The biggest gatekeeper to this is at the beginning - loading in data. Most commonly the paths are set to private directories which means one has to change this code to run it. Setting parent directories in paths like `r path = "../directory/data"` sometimes also leads to errors, especially if the code was written on Windows and reproduced on MacOS. 

### Dependencies
Scientists that switch from GUI statistical softwares to programming languages most often rely on packages to make that transition less painful, which ends up hindering the reproducibilty advantages of coding analyses in open source.

Often, very convoluted, highly specialized packages end up being removed from CRAN, no longer maintained or incompatible with other environments. I would say this reason for non-reproducible analysis is the hardest to fix, as it requires rewriting the analysis with other packages or more complex code. Even the properly maintained packages that belong to the tidyverse family suffer from these issues after multiple updates.

### Containers, environemnts, and container emulators
Ironically, packages created to solve reproducibility issues [end up breaking the code](https://x.com/luce10101/status/1816126972143231172?s=46). If my memory serves me well (and it doesn't), I had issues with reproducing every script that used some kind of container-emulating package, e.g., renv, groundhog, etc.

Unfortunately, although they should work well for installing previous versions of the packages, they cannot install packages that are removed from CRAN, and sometimes even fail to install packages that are still available. This issue then requires removing the container emulatos or the packages they cannot install.

### Deprecated or incorrect functions
Tidyverse might be the biggest culprit when it comes to 

## Slightly-better-than-horrible ways to improve reproducibility



